export const usernameExceptions = [
	'3-UP',
	'Ent!ty',
	'Anti-Hero Charting Team',
	'Jacob Örtengren',
	'Justin?',
	'Jacob Ö',
	'V-King',
	'Mearkk!',
	'Sasquatch-sicle',
	'Delta-V',
	'CTH1:R Team',
	'Enkidu+',
	'die-no-mite',
	'C̡͔̘͈̲̩̺̘͉͕͚̻͍͕̓̏ͥ̿̒ͮͨ̈́̚h̸̯̱͕̻͍̙͖̖̐̏ͮ̌̔̎͛ͮ͌̅͑̓̋́̚͜ͅͅe̡̼̗͖͓̖̺̫̖̮̤̻͔̖̬͓͍̞ͮ̅ͬ͗ͮ͗ͧ̎ͬͪ̄̽ͭ̋ͥ̑̚̚͘̕͟͝z̶̡̥̣̺̘̺̙̬̦͉͈̥͎͓͈̮̺̞̭̄ͤ̊ͨ͒̒ͬ̌̽͋̑ͬ͑̾ͥͭ̆̓̕ỷ͖̰͈̯̲ͮͭ̒̑̐ͨ̚̕͞',
	'Miscellany: Feel Energized',
	'ΩHM',
	'Nene~Chan',
	'Nene-Chan',
	'FreeStyleGames=',
	'Matt$ (Expert)',
	'Hyperbola (Med & Easy)',
	'Matt$',
	'Desert Stream~',
	'T-Shirt',
	'Christoffer Karl�n',
	'does it matter?',
	'FbS-13',
	'ֆהტϣ',
	't-20-07',
	'BigBo-Peep',
	'MewcipuЯR',
	'Blue~',
	'F41LL-GH',
	'Alt-StrumProductions',
	'JakeV-EMI',
	'Andrew-Buch',
	'Atupo-Maruru',
	'Interactive-Music-Productions',
	'Tu mamá en tanga de leopardo',
	'ＬＭＢＥＣＩＬ１８３２',
	'Guitar Hero 3: LOR',
	'nsw1-6',
	'The---Way',
	'george-97',
	'bunny!',
	'TSD-Randy'
]
