/** Default values for known `song.ini` `[Song]` fields. */
export const defaultMetadata = {
	name: 'Unknown Name',
	artist: 'Unknown Artist',
	album: 'Unknown Album',
	genre: 'Unknown Genre',
	year: 'Unknown Year',
	charter: 'Unknown Charter',
	/** Units of ms */ song_length: 0,
	diff_band: -1,
	diff_guitar: -1,
	diff_guitar_coop: -1,
	diff_rhythm: -1,
	diff_bass: -1,
	diff_drums: -1,
	diff_drums_real: -1,
	diff_keys: -1,
	diff_guitarghl: -1,
	diff_guitar_coop_ghl: -1,
	diff_rhythm_ghl: -1,
	diff_bassghl: -1,
	diff_vocals: -1,
	/** Units of ms */ preview_start_time: -1,
	icon: '',
	loading_phrase: '',
	album_track: 16000,
	playlist_track: 16000,
	modchart: false,
	/** Units of ms */ delay: 0,
	hopo_frequency: 0,
	eighthnote_hopo: false,
	multiplier_note: 0,
	sustain_cutoff_threshold: -1,
	chord_snap_threshold: 0,
	video_start_time: 0,
	five_lane_drums: false,
	pro_drums: false,
	end_events: true,
}
